# env params
sparse: false
env_name: ''
# env_name: 'AdroitHandDoor-v1'
# env_name: 'AdroitHandPen-v1'
# env_name: 'AdroitHandHammer-v1'
# env_name: 'AdroitHandRelocate-v1'

# target_performance of oracle
target_performance: 0.6

# learning params
buffer_size: 300000
buffer_size_debug: 100
batch_size: 1024
total_steps: 1000000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.99
learning_rate: 0.0004
exploration_steps: 0

# CCGE params
pretrained_oracle: true
update_oracle: false
confidence_lambda: 0.1

# core SAC params
use_entropy: true
target_entropy: null
target_entropy: -42.0

# AWAC params
lambda_parameter: 0.3
offline_epochs: 10
offline_steps: 100000
online_steps: 900000
reset_memory: false

# eval settings
eval_num_episodes: 100
eval_steps_ratio: 10000

# wingman required params
debug: false
train: false
display: false
evaluate: false

weights_directory: 'weights'
version_number: null
mark_number: 0

increment: false
logging_interval: 10000
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
# wandb_project: 'CCGE2'
wandb_project: 'CCGE2_oracle_search'
