# number of environments to run in parallel
num_envs: 1

# training params
buffer_size: 250000
buffer_size_debug: 10
batch_size: 170
start_epoch: 0
epochs: 1000
repeats_per_buffer: 5 # repeats = repeats_per_buffer + repeats_per_buffer_scale * epoch
repeats_per_buffer_scale: -0.005
critic_update_multiplier: 1
actor_update_multiplier: 1

# exploration settings
exploration_epochs: 50
transitions_per_epoch: 1000

# learning rate and scheduler
starting_LR: 0.001
scheduler_steps: 2
scheduler_gamma: 0.5

# algorithm specifics
reg_lambda: 0.05
confidence_scale: 1.
confidence_cutoff: 0.08
use_entropy: true
target_entropy: -0.5

# eval settings
eval_num_traj: 100
eval_epoch_ratio: 20

# helper params
wandb_project: 'e2SAC'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1
