
# training params
switchup_step: 250000
buffer_size: 30000
buffer_size_debug: 100
batch_size: 300
total_steps: 500000
repeats_per_buffer: 5
max_grad_norm: 0.5
target_network_frequency: 1000

# exploration settings
exploration_steps: 0

# learning rate and exploration rate
learning_rate: 0.001
exploration_epsilon: 0.1

# eval settings
eval_steps_ratio: 5000
eval_num_traj: 20

# helper params
wandb_project: 'ESDDQN'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1

