# env type
env_name: ''
# env_name: 'AntPyBulletEnv-v0'
# env_name: 'HopperPyBulletEnv-v0'
# env_name: 'HumanoidPyBulletEnv-v0'
# env_name: 'HalfCheetahPyBulletEnv-v0'

# training params
buffer_size: 200000
buffer_size_debug: 100
batch_size: 256
total_steps: 200000
repeats_per_buffer: 3 # repeats = repeats_per_buffer + repeats_per_buffer_scale * epoch
repeats_per_buffer_scale: 0.0
critic_update_multiplier: 1
actor_update_multiplier: 1
learning_rate: 0.0004

# exploration settings
exploration_steps: 0

# algorithm specifics
supervision_lambda: 10.
confidence_lambda: 20.
use_entropy: true
target_entropy: null
n_var_samples: 32

# eval settings
eval_num_episodes: 50
eval_steps_ratio: 50000

# helper params
wandb_project: 'e2SAC_pybullet'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1

