# env params
# env_name: 'Ant-v4'
env_name: 'HalfCheetah-v4'
# env_name: 'Hopper-v4'
# env_name: 'Walker2d-v4'

# size of suboptimal policy
sub_size: 200

# learning params
buffer_size: 300000
buffer_size_debug: 100
batch_size: 256
# total_steps: 1000000
total_steps: 250000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.98
learning_rate: 0.0004
exploration_steps: 0

# CCGE params
supervision_lambda: 1.0
confidence_lambda: 200.0

# core SAC params
use_entropy: true
target_entropy: null

# eval settings
eval_num_episodes: 10
eval_steps_ratio: 20000

# wingman required params
debug: false
train: false
display: false
evaluate: false

weights_directory: 'weights'
version_number: null
mark_number: 0

increment: false
epoch_interval: 1
batch_interval: -1
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
wandb_project: 'CCGE2'
