# settings.yaml file

# number of environments to run in parallel
num_envs: 10

# training params
buffer_size: 500000
buffer_size_debug: 10000
batch_size: 300
start_epoch: 0
epochs: 50
transitions_per_epoch: 10000
repeats_per_buffer: 10
critic_update_multiplier: 3
actor_update_multiplier: 1

starting_LR: 0.001
scheduler_steps: 5
scheduler_gamma: 0.5

reg_lambda: 0.01
use_entropy: true
target_entropy: -1.
confidence_scale: 0.5
confidence_cutoff: 0.2

eval_num_traj: 100

# helper params
wandb_project: 'UA3SAC_gym'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1
