
# training params
switchup_epoch: 300
buffer_size: 50000
buffer_size_debug: 100
batch_size: 128
total_steps: 100000
repeats_per_buffer: 3

# exploration settings
exploration_steps: 0

# learning rate and exploration rate
learning_rate: 0.01
exploration_epsilon: 0.05

# eval settings
eval_steps_ratio: 1000
eval_num_episodes: 10

# helper params
wandb_project: 'ESDDQN'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1

