# env params
env_name: 'PyFlyt/QuadX-Waypoints-v0'
agent_hz: 30
num_targets: 5
context_length: 2

# learning params
buffer_size: 300000
buffer_size_debug: 100
batch_size: 256
total_steps: 1000000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.99
learning_rate: 0.0005
exploration_steps: 0

# CCGE params
pretrained_oracle: true
update_oracle: false
confidence_lambda: 0.1

# AWAC params
lambda_parameter: 0.1
offline_epochs: 10
offline_steps: 200000
online_steps: 800000
reset_memory: false

# core SAC params
use_entropy: true
target_entropy: -8

# eval settings
eval_num_episodes: 50
eval_steps_ratio: 10000

# wingman required params
debug: false
train: false
display: false
evaluate: false
render_gif: false

weights_directory: 'weights'
version_number: null
mark_number: 0

increment: false
logging_interval: 10000
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
wandb_project: 'CCGE2'
