# env params
env_name: ''
# env_name: 'Ant-v4'
# env_name: 'HalfCheetah-v4'
# env_name: 'Hopper-v4'
env_name: 'Walker2d-v4'

# target_performance of oracle
target_performance: 3000

# learning params
buffer_size: 300000
buffer_size_debug: 100
batch_size: 256
total_steps: 1000000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.99
learning_rate: 0.0004
exploration_steps: 0

# CCGE params
pretrained_oracle: true
update_oracle: false
confidence_lambda: 1.0

# core SAC params
use_entropy: true
target_entropy: null

# AWAC params
lambda_parameter: 0.05
offline_epochs: 10
offline_steps: 100000
online_steps: 900000
reset_memory: false

# eval settings
eval_num_episodes: 100
eval_steps_ratio: 10000

# wingman required params
debug: false
train: false
display: false
evaluate: false

weights_directory: 'weights'
version_number: null
mark_number: 0

increment: false
logging_interval: 10000
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
wandb_project: 'CCGE2'
