# training params
buffer_size: 150000
buffer_size_debug: 100
batch_size: 150
total_steps: 150000
repeats_per_buffer: 5 # repeats = repeats_per_buffer + repeats_per_buffer_scale * epoch
repeats_per_buffer_scale: -0.005
critic_update_multiplier: 1
actor_update_multiplier: 1
learning_rate: 0.0004

# exploration settings
exploration_steps: 0

# algorithm specifics
supervision_lambda: 10.
confidence_lambda: 3.
use_entropy: true
target_entropy: 0.5
n_var_samples: 32

# eval settings
eval_num_episodes: 20
eval_steps_ratio: 5000

# helper params
wandb_project: 'e2SAC_carracing'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1
