# environment settings
agent_hz: 10

# learning params
buffer_size: 50000
buffer_size_debug: 100
batch_size: 256
total_steps: 500000
repeats_per_buffer: 3
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.99
learning_rate: 0.0004
exploration_steps: 0
random_rollover: false

# CCGE params
update_oracle: false
confidence_lambda: 0.3

# core SAC params
use_entropy: true
target_entropy: null

# eval settings
eval_num_episodes: 20
eval_steps_ratio: 10000

# wingman required params
debug: false
train: false
display: false
evaluate: false

weights_directory: 'weights'
version_number: null
mark_number: 0
log_status: false

increment: false
logging_interval: 10000
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
# wandb_project: 'CCGE2'
wandb_project: 'CCGE2_oracle_search'
