# training params
buffer_size: 30000
buffer_size_debug: 128
batch_size: 128
total_steps: 150000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
learning_rate: 0.00005
discount_factor: 0.96

# exploration settings
exploration_steps: 0

# algorithm specifics
supervision_lambda: 1.
confidence_lambda: 5.
use_entropy: true
target_entropy: null
n_var_samples: 16

# eval settings
eval_num_episodes: 50
eval_steps_ratio: 5000

# helper params
wandb_project: 'carracing_normal'
weights_directory: 'weights'
optim_weights_directory: 'optim_weights'
net_version: ''
net_number: 0
epoch_interval: 1
batch_interval: -1
