# env params
env_name: 'PyFlyt/SimpleWaypointEnv-v0'
num_targets: 5
context_len: 3

# learning params
buffer_size: 500000
buffer_size_debug: 100
batch_size: 256
total_steps: 1000000
repeats_per_buffer: 1
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.99
learning_rate: 0.0005
exploration_steps: 0

# CCGE params
pretrained_oracle: true
update_oracle: false
confidence_lambda: 0.1

# core SAC params
use_entropy: true
target_entropy: -12.0

# eval settings
eval_num_episodes: 50
eval_steps_ratio: 10000

# wingman required params
debug: false
train: false
display: false
evaluate: false

weights_directory: 'weights'
version_number: null
mark_number: 0

increment: false
logging_interval: 10000
max_skips: 5
greater_than: 0.0

wandb: false
wandb_name: ''
wandb_notes: ''
wandb_id: ''
wandb_entity: 'jjshoots'
wandb_project: 'CCGE2'
